编写一个NumPy程序以在您的系统中打印NumPy版本。

In [ ]:
import numpy as np
print(np.__version__)


编写一个NumPy程序，将数值列表转换为一维NumPy数组。
预期输出：
原始列表：[12.23、13.32、100、36.32]
一维numpy数组：[12.23 13.32 100. 36.32]

In [ ]:
import numpy as np
l = [12.23, 13.32, 100, 36.32]
print("Original List:",l)
a = np.array(l)
print("One-dimensional numpy array: ",a)


编写一个NumPy程序以创建一个3x3矩阵，其值的范围为2到10。
预期输出：
[[2 3 4]
[5 6 7]
[8 9 10]]

In [ ]:

import numpy as np
x =  np.arange(2, 11).reshape(3,3)
print(x)


编写一个NumPy程序以创建一个3x3矩阵，其值的范围为2到10。
预期输出：
[[2 3 4]
[5 6 7]
[8 9 10]]

In [ ]:

import numpy as np
x =  np.arange(2, 11).reshape(3,3)
print(x)


编写一个NumPy程序以创建大小为10的空向量并将第六个值更新为11。
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
更新第六个值到11
[0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [1]:

import numpy as np
x = np.zeros(10)
print(x)
print("Update sixth value to 11")
x[6] = 11
print(x)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


编写一个NumPy程序以创建一个值在12到38之间的数组。
预期输出：
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]

In [ ]:
import numpy as np
x = np.arange(12, 38)
print(x)


编写一个NumPy程序以反转数组（第一个元素变为最后一个元素）。
原始数组：
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
反向数组：
[37 36 35 34 33 32 31 30 29 28 27 [26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [2]:
import numpy as np
import numpy as np
x = np.arange(12, 38)
print("Original array:")
print(x)
print("Reverse array:")
x = x[::-1]
print(x)


Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


将NumPy程序写入转换为浮点类型的数组。
样本输出：
原始数组
[1、2、3、4]
转换为浮点类型的数组：
[1. 2. 3. 4.]

In [ ]:
import numpy as np
import numpy as np
a = [1, 2, 3, 4]
print("Original array")
print(a)
x = np.asfarray(a)
print("Array converted to a float type:")
print(x)


编写一个NumPy程序以创建一个2d数组，其边界为1，内部为0。
预期输出：
原始数组：
[[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
[1。 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1.]]
边界上为1，数组
[[1. 1. 1. 1. 1.]]
[1. 0. 0. 0. 1.]
[1. 0. 0. 0. 1.]
[1. 0. 0. 0. 1.]

In [ ]:
import numpy as np
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)


编写一个NumPy程序，在现有数组周围添加边框（用0填充）。
预期输出：
原始数组：
[[1. 1. 1.]
[1. 1. 1.]
[1. 1. 1.]]
边框上为1，数组内为0
[[0. 0. 0. 0. 0.]
[0. 1. 1. 1. 0.]
[0. 1. 1. 1. 0.]
[0. 1. 1. 1. 0.]
[0. 0. 0. 0. 0.]]

In [ ]:
import numpy as np
x = np.ones((3,3))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)


编写一个NumPy程序以创建8x8矩阵，并用棋盘图案填充它。
棋盘模式：
[[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]

In [3]:
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)


Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


编写一个NumPy程序，以将列表和元组转换为数组。
数组列表：
[1 2 3 4 5 6 7 8]
元组数组：
[[8 4 6]
[1 2 3]]

In [ ]:
import numpy as np
my_list = [1, 2, 3, 4, 5, 6, 7, 8]
print("List to array: ")
print(np.asarray(my_list))
my_tuple = ([8, 4, 6], [1, 2, 3])
print("Tuple to array: ")
print(np.asarray(my_tuple))


编写一个NumPy程序，将值附加到数组的末尾。
预期输出：
原始数组：
[10，20，30]
将值附加到数组末尾后：
[10 20 30 40 50 60 70 80 90]

In [ ]:
import numpy as np
x = [10, 20, 30]
print("Original array:")
print(x)
x = np.append(x, [[40, 50, 60], [70, 80, 90]])
print("After append values to the end of the array:")
print(x)


编写一个NumPy程序以创建一个空数组和一个完整数组。
预期输出：
[6.93270651e-310 1.59262180e-316 6.93270559e-310 6.93270665e-310]
[6.93270667e-310 6.93270671e-310 6.93270668e-310 6.93270483e-310]
[6.93270668e-310 6.93270671e -310 6.93270370e-310 6.93270488e-310]]
[[6 6 6]
[6 6 6]
[6 6 6]]

In [ ]:
import numpy as np
# Create an empty array
x = np.empty((3,4))
print(x)
# Create a full array
y = np.full((3,3),6)
print(y)


编写一个NumPy程序，将摄氏度的值转换为华氏度。摄氏度值存储在NumPy数组中。
Sample Array [0，12，45.21，34，99.91]
预期输出：
华氏度值：
[0. 12. 45.21 34. 99.91]
摄氏度度值：
[-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

In [4]:
import numpy as np
fvalues = [0, 12, 45.21, 34, 99.91]
F = np.array(fvalues)
print("Values in Fahrenheit degrees:")
print(F)
print("Values in  Centigrade degrees:") 
print(5*F/9 - 5*32/9)


Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91]
Values in  Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


编写一个NumPy程序以查找复数数组的实部和虚部。
预期输出：
原始数组[1.00000000 + 0.j 0.70710678 + 0.70710678j]
数组的实部：
[1. 0.70710678]
数组的虚部：
[0. 0.70710678]

In [ ]:
import numpy as np
x = np.sqrt([1+0j])
y = np.sqrt([0+1j])
print("Original array:x ",x)
print("Original array:y ",y)
print("Real part of the array:")
print(x.real)
print(y.real)
print("Imaginary part of the array:")
print(x.imag)
print(y.imag)

编写一个NumPy程序，以查找数组的元素数，一个数组元素的长度（以字节为单位）和元素消耗的总字节数。
预期输出：
数组的大小：3
一个数组元素的长度（以字节为单位）：8数组元素
消耗的总字节数：24

In [ ]:
import numpy as np
x = np.array([1,2,3], dtype=np.float64)
print("Size of the array: ", x.size)
print("Length of one array element in bytes: ", x.itemsize)
print("Total bytes consumed by the elements of the array: ", x.nbytes)


编写一个NumPy程序，以测试一维数组的每个元素是否也存在于第二个数组中。
编写一个NumPy程序，以测试一维数组的每个元素是否也存在于第二个数组中。

In [5]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [0, 40]
print("Array2: ",array2)
print("Compare each element of array1 and array2")
print(np.in1d(array1, array2))


Array1:  [ 0 10 20 40 60]
Array2:  [0, 40]
Compare each element of array1 and array2
[ True False False  True False]


编写一个NumPy程序以查找两个数组之间的公共值。
预期输出：
Array1：[0 10 20 40 60]
Array2：[10、30、40]
两个数组之间的公共值：
[10 40]

In [ ]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))


编写一个NumPy程序以获取数组的唯一元素。
预期输出：
原始数组：
[10 10 20 20 30 30]
上面的数组的唯一元素：
[10 20 30]
原始数组：
[[1 1]
[2 3]]
上面的数组的唯一元素：
[1 2 3]

In [6]:
import numpy as np
x = np.array([10, 10, 20, 20, 30, 30])
print("Original array:")
print(x)
print("Unique elements of the above array:")
print(np.unique(x))
x = np.array([[1, 1], [2, 3]])
print("Original array:")
print(x)
print("Unique elements of the above array:")
print(np.unique(x))


Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
Original array:
[[1 1]
 [2 3]]
Unique elements of the above array:
[1 2 3]


编写一个NumPy程序来查找两个数组的集合差。设置差异将返回array1中不在array2中的排序后的唯一值。
预期输出：
Array1：[0 10 20 40 60 80]
Array2：[10、30、40、50、70、90]
设置两个数组之间的差：
[0 20 60 80]

In [ ]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ",array2)
print("Unique values in array1 that are not in array2:")
print(np.setdiff1d(array1, array2))


编写一个NumPy程序来查找两个数组的异或集。Set Exclusive-or将返回仅在输入数组中一个（不是两个）中排序的唯一值。
Array1：[0 10 20 40 60 80]
Array2：[10、30、40、50、70]
仅在输入数组之一（不是两个）中的唯一值：
[0 20 30 50 60 70 80]

In [7]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ",array2)
print("Unique values that are in only one (not both) of the input arrays:")
print(np.setxor1d(array1, array2))


Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]


编写一个NumPy程序来查找两个数组的并集。Union将返回两个输入数组之一中唯一的，已排序的值数组。
Array1：[0 10 20 40 60 80]
Array2：[10、30、40、50、70]
在两个输入数组之一中的值的唯一排序数组：
[0 10 20 30 40 50 60 70 80]

In [ ]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ",array2)
print("Unique sorted array of values that are in either of the two input arrays:")
print(np.union1d(array1, array2))


编写一个NumPy程序以测试数组中的所有元素是否都为True。
注意：0在NumPy中的计算结果为False。

In [ ]:
import numpy as np
print(np.all([[True,False],[True,True]]))
print(np.all([[True,True],[True,True]]))
print(np.all([10, 20, 0, -50]))
print(np.all([10, 20, -50]))

编写一个NumPy程序，以测试沿给定轴的任何数组元素的求值是否为True。
注意：0在NumPy中的计算结果为False。

In [ ]:
import numpy as np
print(np.any([[False,False],[False,False]]))
print(np.any([[True,True],[True,True]]))
print(np.any([10, 20, 0, -50]))
print(np.any([10, 20, -50]))


编写一个NumPy程序，通过重复来构造一个数组。
样本数组：[1、2、3、4]
预期输出：
原始数组
[1、2、3、4]
重复2次
[1 2 3 4 1 2 3 4]
重复3次
[1 2 3 4 1 2 3 4 1 2 3 4]

In [8]:
import numpy as np
a = [1, 2, 3, 4]
print("Original array")
print(a)
print("Repeating 2 times")
x = np.tile(a, 2)
print(x)
print("Repeating 3 times")
x = np.tile(a, 3)
print(x)


Original array
[1, 2, 3, 4]
Repeating 2 times
[1 2 3 4 1 2 3 4]
Repeating 3 times
[1 2 3 4 1 2 3 4 1 2 3 4]


编写一个NumPy程序来重复数组的元素。
预期输出：
[3 3 3 3]
[1 1 2 2 3 3 4 4]

In [ ]:
import numpy as np
x = np.repeat(3, 4)
print(x)
x = np.array([[1,2],[3,4]])
print(np.repeat(x, 2))


编写一个NumPy程序，以沿着数组的给定轴查找最大值和最小值的索引。
原始数组：[1 2 3 4 5 6]
最大值：5
最小值：0

In [ ]:
import numpy as np
x = np.array([1, 2, 3, 4, 5, 6])
print("Original array: ",x)
print("Maximum Values: ",np.argmax(x))
print("Minimum Values: ",np.argmin(x))


编写一个NumPy程序，使用numpy比较两个数组。
数组a：[1 2]
数组b：[4 5]
a> b
[False False]
a> = b
[False False]
a <b
[True True]
a <= b
[True True]

In [ ]:
import numpy as np
a = np.array([1, 2])
b = np.array([4, 5])
print("Array a: ",a)
print("Array b: ",b)
print("a > b")
print(np.greater(a, b))
print("a >= b")
print(np.greater_equal(a, b))
print("a < b")
print(np.less(a, b))
print("a <= b")
print(np.less_equal(a, b))


编写一个NumPy程序，以沿数组的第一个，最后一个轴对进行排序。
样本数组：[[2,5]，[4,4]]
预期输出：
原始数组：
[[4 6]
[2 1]]
沿第一个轴排序：
[[2 1]
[4 6 ] ]
沿最后一个轴排序：
[[1 2]
[4 6]]

In [ ]:
import numpy as np
a = np.array([[4, 6],[2, 1]])
print("Original array: ")
print(a)
print("Sort along the first axis: ")
x = np.sort(a, axis=0)
print(x)
print("Sort along the last axis: ")
y = np.sort(x, axis=1)
print(y)


编写一个NumPy程序，以对成对的名字和姓氏返回其索引。（首先按姓氏，然后按名字）。
first_names =（贝塞（Betsey），雪莱（Shelley），莱恩（Lanell），创世纪（Genesis），玛格丽
（Margery））last_names =（战斗（Battle），布里恩（Brien），普洛特纳（Plotner），斯塔尔（Stahl），伍拉姆（Woolum））
预期输出：
[1 3 2 4 0]

In [ ]:
import numpy as np
first_names =    ('Margery', 'Betsey', 'Shelley', 'Lanell', 'Genesis')
last_names = ('Woolum', 'Battle', 'Plotner', 'Brien', 'Stahl')
x = np.lexsort((first_names, last_names))
print(x)


编写一个NumPy程序，以获取给定数组中大于10的元素的值和索引。
原始数组：
[[0 10 20]
[20 30 40]]
大于10的值= [20 20 30 40]
它们的索引为（array（[0，1，1，1]]，array（[ 2，0，1，2]）））

In [ ]:
原始数组：
[[0 10 20]
[20 30 40]]
大于10的值= [20 20 30 40]
它们的索引为（array（[0，1，1，1]），array（[ 2，0，1，2]）））

编写一个NumPy程序将NumPy数组保存到文本文件。

In [ ]:
import numpy as np
a = np.arange(1.0, 2.0, 36.2)
np.savetxt('file.out', a, delimiter=',')


编写一个NumPy程序以查找NumPy数组的内存大小。
预期输出：
128字节

In [ ]:
import numpy as np
n = np.zeros((4,4))
print("%d bytes" % (n.size * n.itemsize))


编写一个NumPy程序来创建一个1的数组和一个0的数组。
预期输出：
创建一个零数组
默认类型为float
[[0. 0.]]
类型更改为int
[[0 0]]
创建一个整数数组
默认类型为float
[[1. 1.]]
将更改类型更改为int
[[1 1]]

In [ ]:
import numpy as np
print("Create an array of zeros")
x = np.zeros((1,2))
print("Default type is float")
print(x)
print("Type changes to int")
x = np.zeros((1,2), dtype = np.int)
print(x)
print("Create an array of ones")
y= np.ones((1,2)) 
print("Default type is float")
print(y)
print("Type changes to int")
y = np.ones((1,2), dtype = np.int)
print(y)


编写一个NumPy程序来更改数组的维数。
预期输出：
6行和0列
（6，）
（3，3）-> 3行和3列
[[1 2 3]
[4 5 6]
[7 8 9]]
将数组形状更改为（3，3）-> 3行3列
[[1 2 3]
[4 5 6]
[7 8 9]]

In [ ]:
import numpy as np
x = np.array([1, 2, 3, 4, 5, 6])
print("6 rows and 0 columns")
print(x.shape)

y = np.array([[1, 2, 3],[4, 5, 6],[7,8,9]])
print("(3, 3) -> 3 rows and 3 columns ")
print(y)

x = np.array([1,2,3,4,5,6,7,8,9])
print("Change array shape to (3, 3) -> 3 rows and 3 columns ")
x.shape = (3, 3)
print(x)


编写一个NumPy程序来创建一个连续的扁平数组。
原始数组：
[[10 20 30]
[20 40 50]]
新的展平数组：
[10 20 30 20 40 50]

In [ ]:
import numpy as np
x = np.array([[10, 20, 30], [20, 40, 50]])
print("Original array:")
print(x)
y = np.ravel(x)
print("New flattened array:")
print(y)


编写一个NumPy程序来创建一个大小为2 x 3的二维数组（由4个字节的整数元素组成），并打印数组的形状，类型和数据类型。
预期输出：

（2，3）
int32

In [ ]:
import numpy as np
x = np.array([[2, 4, 6], [6, 8, 10]], np.int32)
print(type(x))	
print(x.shape)
print(x.dtype)


编写一个NumPy程序，以在不更改数据的情况下为数组创建新形状.
重塑3x2：
[[1 2]
[3 4]
[5 6]]
重塑2x3：
[[1 2 3]
[4 5 6]]

In [ ]:
import numpy as np
x = np.array([1, 2, 3, 4, 5, 6])
y = np.reshape(x,(3,2))
print("Reshape 3x2:")
print(y)
z = np.reshape(x,(2,3))
print("Reshape 2x3:")
print(z)


编写一个NumPy程序来更改数组的数据类型。
预期输出：
[[2 4 6]
[6 8 10]]
数组x的数据类型为：int32
新建类型：float64
[[2. 4. 6.]
[6. 8. 10.]]

In [ ]:
import numpy as np
x = np.array([[2, 4, 6], [6, 8, 10]], np.int32)
print(x)
print("Data type of the array x is:",x.dtype)
# Change the data type of x
y = x.astype(float)
print("New Type: ",y.dtype)
print(y)


编写一个NumPy程序以创建一个新的3 * 5数组，并填充2。
预期输出：
[[2 2 2 2 2]
[2 2 2 2 2]
[2 2 2 2 2]]
[[2 2 2 2 2]
[2 2 2 2 2]
[2 2 2 2 2]]

In [ ]:
import numpy as np
#using no.full
x = np.full((3, 5), 2, dtype=np.uint)
print(x)
#using no.ones
y = np.ones([3, 5], dtype=np.uint) *2
print(y)


编写一个NumPy程序来创建一个10的数组，该数组具有与给定数组相同的形状和类型。
样本数组：x = np.arange（4，dtype = np.int64）
预期输出：
[10 10 10 10]

In [ ]:
import numpy as np
x = np.arange(4, dtype=np.int64)
y = np.full_like(x, 10)
print(y)


编写一个NumPy程序来创建一个3-D数组，其中对角线为1，其他位置为零。
预期输出：
[[1. 0. 0.]
[0. 1. 0.]
[0. 0. 1.]]

In [ ]:
import numpy as np
x = np.eye(3)
print(x)


编写一个NumPy程序来创建一个二维数组，其对角线等于[4、5、6、8]，其他地方为0。
预期输出：
[[4 0 0 0]
[0 5 0 0]
[0 0 6 0]
[0 0 0 8]]

In [ ]:
import numpy as np
x =  np.diagflat([4, 5, 6, 8])
print(x)


编写一个NumPy程序以创建一个从0到50的一维数组和一个从10到50的数组。
预期输出：
从0到50的数组：
[0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
从10到50的数组：
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

In [ ]:
import numpy as np
x = np.arange(50)
print("Array from 0 to 50:")
print(x)
x = np.arange(10, 50)
print("Array from 10 to 50:")
print(x)


编写一个NumPy程序以创建一个2.5维之间由30个均匀间隔的元素组成的一维数组。和6.5（含）。
预期输出：
[2.5 2.63793103 2.77586207 2.9137931 3.05172414 3.18965517
3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
5.81034483 5.94827586 6.0862069 6.22413793 6.36206897 6.5]

In [ ]:
import numpy as np
x = np.linspace(2.5, 6.5, 30)
print(x)


编写一个NumPy程序以创建一个由20个元素组成的1-D数组，该数组在2到5（不包括对数）之间的对数刻度上均匀分布。
预期输出：
[100 141.25375446 199.5262315 281.83829313
398.10717055 562.34132519 794.32823472 1122.0184543
1584.89319246 2238.72113857 3162.27766017 4466.83592151
6309.5734448 8912.50938134 12589.25411794 17782.79410039
25118.8643151 35481.33892336 50118.72336273 70794.57843841]

In [ ]:
import numpy as np
x =  np.logspace(2., 5., 20, endpoint=False)
print(x)


编写一个NumPy程序来创建一个数组，看起来像下面的数组。
预期输出：
[[0. 0. 0.]
[1. 0. 0.]
[1. 1. 0.]
[1. 1. 1.]]

In [ ]:
import numpy as np
x = np.tri(4, 3, -1)
print(x)


编写一个NumPy程序来创建一个类似于下面的数组的数组。
预期输出：
[[2 3 4]
[5 6 7]
[0 9 10]
[0 0 13]]

In [ ]:
import numpy as np
x = np.triu(np.arange(2, 14).reshape(4, 3), -1)
print(x)


编写一个NumPy程序，将3-D数组折叠为一维数组。
预期输出：
3-D数组：
[[1. 0. 0.]
[0. 1. 0.]
[0. 0. 1.]]
一维数组：
[1. 0. 0. 0 .1. 0. 0. 0. 1.]

In [ ]:
import numpy as np
x = np.eye(3)
print("3-D array:")
print(x)
f = np.ravel(x, order='F')
print("One dimension array:")
print(f)


编写一个NumPy程序以查找指定数组的第4个元素。
预期输出：
[[2 4 6]
[6 8 10]]
数组的第一部分：
6

In [ ]:
import numpy as np
x = np.array([[2, 4, 6], [6, 8, 10]], np.int32)
print(x)
e1 = x.flat[3]
print("Forth e1ement of the array:")
print(e1)
