In [ ]:
51.编写一个NumPy程序来交换一个数组的两个轴

In [22]:
import numpy as np
#example 1
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('A = ',A)
B = np.transpose(A)
print('B = ',B)
#example 2
C = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[4,5,6],[1,2,3],[7,8,9]]])
print('C = ',C)
D = np.swapaxes(C,0,1)#交换0轴和1轴
print('D = ',D)

A =  [[1 2 3]
 [4 5 6]
 [7 8 9]]
B =  [[1 4 7]
 [2 5 8]
 [3 6 9]]
C =  [[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[4 5 6]
  [1 2 3]
  [7 8 9]]]
D =  [[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [1 2 3]]

 [[7 8 9]
  [7 8 9]]]


In [ ]:
52.编写一个NumPy程序，将数组的轴移动到新的位置。其他轴保持原来的顺序

In [10]:
import numpy as np
x = np.zeros((2, 3, 4))
print(x.shape)
print(np.moveaxis(x, 0, -1).shape)
print(np.moveaxis(x, -1, 0).shape)

(2, 3, 4)
(3, 4, 2)
(4, 2, 3)


In [ ]:
53.编写一个NumPy程序，将指定的轴向后移动，直到它位于给定的位置。

将下列第三个阵列轴移动到第一个位置。

In [15]:
import numpy as np
x = np.ones((2,3,4,5,2))#0,1,2,3轴
print(np.rollaxis(x, 4, 1).shape)#将3轴移到1轴

(2, 2, 3, 4, 5)


In [ ]:
54.编写一个NumPy程序，将指定的输入转换为至少具有一个维度的数组。

In [3]:
import numpy as np
x = 12.0
print(np.atleast_1d(x))
x = np.arange(6.0).reshape(2,3)
print(np.atleast_1d(x))
print(np.atleast_1d(1,[3,4]))

[12.]
[[0. 1. 2.]
 [3. 4. 5.]]
[array([1]), array([3, 4])]


In [ ]:
55.编写一个NumPy程序，将输入视为至少具有二维、三维的数组。

In [24]:
import numpy as np
x = 10
print("输入至少两维的矩阵:")
print(np.atleast_1d(x))
x = np.arange(4.0).reshape(2, 2)
print(np.atleast_1d(x))
print("输入至少三维的矩阵:")
x =15
print(np.atleast_3d(x))
x = np.arange(3.0)
print(np.atleast_3d(x))

输入至少两维的矩阵:
[10]
[[0. 1.]
 [2. 3.]]
输入至少三维的矩阵:
[[[15]]]
[[[0.]
  [1.]
  [2.]]]


In [ ]:
56.编写一个NumPy程序，在二维数组中插入一个新轴。

In [27]:
import numpy as np
x = np.zeros((3, 4))
print('x = ',x)
y = np.expand_dims(x, axis=1)
print('y = ',y)
print(y.shape)

x =  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
y =  [[[0. 0. 0. 0.]]

 [[0. 0. 0. 0.]]

 [[0. 0. 0. 0.]]]
(3, 1, 4)


In [ ]:
57. 编写NumPy程序从指定的形状中删除单维条目。

In [34]:
import numpy as np
x = np.zeros((3, 1, 4))
print('x = ',x)
print(np.squeeze(x))
#squeeze():删除单维条目，如果x没有单维条目，则x不会改变
print(np.squeeze(x).shape)

x =  [[[0. 0. 0. 0.]]

 [[0. 0. 0. 0.]]

 [[0. 0. 0. 0.]]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(3, 4)


In [ ]:
58. 编写一个NumPy程序来连接两个二维数组。

In [32]:
import numpy as np
a = np.array([[0, 1, 3], [5, 7, 9]])
b = np.array([[0, 2, 4], [6, 8, 10]])
c = np.concatenate((a, b), 1)#矩阵相接
print(c)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


In [ ]:
59. 编写一个NumPy程序将一维数组作为列转换为二维数组。

In [37]:
import numpy as np
a = np.array((10,20,30))
b = np.array((40,50,60))
print(a)
print(b)
c = np.column_stack((b, a))#按列拼接,a,b顺序影响矩阵
print(c)

[10 20 30]
[40 50 60]
[[40 10]
 [50 20]
 [60 30]]


In [ ]:
60. 编写一个NumPy程序将两个一维数组(按顺序深度(沿第三轴))转换为一个二维数组。

In [ ]:
import numpy as np
a = np.array([[10],[20],[30]])
b = np.array([[40],[50],[60]])
c = np.dstack((a, b))
print(c)

In [ ]:
61.编写一个NumPy程序，将一个14个元素的数组拆分为3个数组，每个数组按原来的顺序包含2、4和8个元素。

In [ ]:
import numpy as np
x = np.arange(1, 15)
print("初始矩阵:",x)
print("拆分后:")
print(np.split(x, [2, 6]))

In [ ]:
62. 编写一个NumPy程序，将形状为4x4的数组沿第二轴拆分为两个数组。

In [ ]:
import numpy as np
x = np.arange(16).reshape((4, 4))
print("Original array:",x)
print("After splitting horizontally:")
print(np.hsplit(x, [2, 6]))

In [ ]:
63.编写一个NumPy程序以获取数组中非零元素的数量。

In [ ]:
import numpy as np
x = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array:")
print(x)
print("Number of non zero elements in the above array:")
print(np.count_nonzero(x))

In [ ]:
64.编写一个NumPy程序，以创建一个5x5矩阵，行值的范围为0到4。

In [ ]:
import numpy as np
x = np.zeros((5,5))
print("Original array:")
print(x)
print("Row values ranging from 0 to 4.")
x += np.arange(5)
print(x)

In [ ]:
65.编写一个NumPy程序来测试数组中是否存在指定的值。

In [ ]:
import numpy as np
x = np.array([[1.12, 2.0, 3.45], [2.33, 5.12, 6.0]], float) 
print("Original array:")
print(x)
print(2 in x)
print(0 in x)
print(6 in x)
print(2.3 in x)
print(5.12 in x)

In [ ]:
66.编写一个NumPy程序以创建大小为10的向量，其值的范围从0到1，均不包括在内。

In [ ]:
import numpy as np
x = np.linspace(0,1,12,endpoint=True)[1:-1]
print(x)

In [ ]:
67.编写一个NumPy程序以使数组不可变（只读）。

In [ ]:
import numpy as np
x = np.zeros(10)
x.flags.writeable = False
print("Test the array is read-only or not:")
print("Try to change the value of the first element:")
x[0] = 1

In [ ]:
68.编写一个NumPy程序（使用numpy）以将3或5的所有倍数之和小于100。

In [ ]:
import numpy as np
x = np.arange(1, 100)
# find  multiple of 3 or 5
n= x[(x % 3 == 0) | (x % 5 == 0)]
print(n[:1000])
# print sum the numbers
print(n.sum())

In [ ]:
69.编写一个NumPy程序以创建一个包含10 ^ 3个元素的数组。

In [ ]:
import numpy as np
x = np.arange(1e3)
print(x)

In [ ]:
70.编写一个NumPy程序以创建显示numpy数组的每个元素。

In [ ]:
import numpy as np
x = np.arange(12).reshape(3, 4)
for x in np.nditer(x):
    print(x,end=' ')
print()

In [ ]:
71.编写一个NumPy程序，以Fortran顺序创建和显示numpy数组的每个元素。

In [ ]:
import numpy as np
x = np.arange(12).reshape(3, 4)
print("Elements of the array in Fortan array:")
for x in np.nditer(x, order="F"):
    print(x,end=' ')
print("\n")

In [ ]:
72.编写一个NumPy程序来创建5x5x5的1的多维数据集。

In [ ]:
import numpy as np
x = np.zeros((5, 5, 5)).astype(int) + 1
print(x)

In [ ]:
73.编写一个NumPy程序，创建一个（3，4）形状的数组，将每个元素值乘以3，然后显示新数组。

In [ ]:
import numpy as np
x= np.arange(12).reshape(3, 4)
print("Original array elements:")
print(x)
for a in np.nditer(x, op_flags=['readwrite']):
    a[...] = 3 * a
print("New array elements:")
print(x)

In [ ]:
74.编写一个NumPy程序，将一维和二维数组组合在一起，并显示它们的元素。

In [ ]:
import numpy as np
x = np.arange(4)
print("One dimensional array:")
print(x)
y = np.arange(8).reshape(2,4)
print("Two dimensional array:")
print(y)
for a, b in np.nditer([x,y]):
    print("%d:%d" % (a,b),)

In [ ]:
75.编写一个NumPy程序，以创建一个零数组和三种列类型（整数，浮点数，字符）。

In [ ]:
import numpy as np
x = np.zeros((3,), dtype=('i4,f4,a40'))
new_data = [(1, 2., "Albert Einstein"), (2, 2., "Edmond Halley"), (3, 3., "Gertrude B. Elion")]
x[:] = new_data
print(x)

In [ ]:
76.编写一个NumPy程序来创建一个功能多维数据集，该多维数据集可对数组的所有元素进行多维数据集处理。

In [ ]:
import numpy as np
def cube(e):
    it = np.nditer([e, None])
    for a, b in it:
        b[...] = a*a*a
    return it.operands[1]
print(cube([1,2,3]))

In [ ]:
77.编写一个NumPy程序以创建（3，4）形状的数组，并将数组元素转换为较小的块。

In [ ]:
import numpy as np
x= np.arange(12).reshape(3, 4)
print("Original array elements:")
print(x)
print("Above array in small chuncks:")
for a in np.nditer(x, flags=['external_loop'], order='F'):
    print(a)

In [ ]:
78.编写一个NumPy程序，从一个（平坦的）数组列表创建一个记录数组。

In [ ]:
import numpy as np
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])

In [ ]:
79.编写一个NumPy程序以生成通用的类似于2D高斯的数组。

In [ ]:
import numpy as np
x, y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d = np.sqrt(x*x+y*y)
sigma, mu = 1.0, 0.0
g = np.exp(-( (d-mu)**2 / ( 2.0 * sigma**2 ) ) )
print("2D Gaussian-like array:")
print(g)

In [ ]:
80.编写一个NumPy程序，将NumPy数组转换为Python列表结构。

In [ ]:
import numpy as np
x= np.arange(6).reshape(3, 2)
print("Original array elements:")
print(x)
print("Array to list:")
print(x.tolist())

In [ ]:
81.编写一个NumPy程序以按列访问数组。

In [ ]:
import numpy as np
x= np.arange(9).reshape(3,3)
print("Original array elements:")
print(x)
print("Access an array by column:")
print("First column:")
print(x[:,0])
print("Second column:")
print(x[:,1])
print("Third column:")
print(x[:,2])

In [ ]:
82.编写一个NumPy程序，将浮点值的numpy数组转换为整数值的numpy数组。

In [ ]:
import numpy as np
x= np.array([[12.0, 12.51], [2.34, 7.98], [25.23, 36.50]])
print("Original array elements:")
print(x)
print("Convert float values to integer values:")
print(x.astype(int))

In [ ]:
83.编写一个NumPy程序，以给定的精度显示浮点值的numpy数组元素。

In [ ]:
import numpy as np
x=np.array([ 0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 0.69746349,             
  0.35399976, 0.99469633, 0.0694458, 0.54711478]) 
print("Original array elements:")
print(x)
print("Print array values with precision 3:")
np.set_printoptions(precision=3)
print(x)

In [ ]:
84.编写一个NumPy程序来禁止对numpy数组中的小数使用科学计数法。

In [ ]:
import numpy as np
x=np.array([1.6e-10, 1.6, 1200, .235]) 
print("Original array elements:")
print(x)
print("Print array values with precision 3:")
np.set_printoptions(suppress=True)
print(x)

In [ ]:
85.编写一个NumPy程序，以从生成器创建一个由10个整数组成的numpy数组。

In [ ]:
import numpy as np
iterable = (x for x in range(10))
print(np.fromiter(iterable, np.int))

In [ ]:
86.编写一个NumPy程序，了解如何向numpy数组添加额外的列。

In [ ]:
import numpy as np
x = np.array([[10,20,30], [40,50,60]])
y = np.array([[100], [200]])
print(np.append(x, y, axis=1))

In [ ]:
87.编写一个NumPy程序以在numpy数组中查找唯一的行。

In [ ]:
import numpy as np
x = np.array([[20, 20, 20, 0],
              [0, 20, 20, 20],
              [0, 20, 20, 20],
              [20, 20, 20, 0],
              [10, 20, 20,20]])
print("Original array:")
print(x)
y = np.ascontiguousarray(x).view(np.dtype((np.void, x.dtype.itemsize * x.shape[1])))
_, idx = np.unique(y, return_index=True)

unique_result = x[idx]
print("Unique rows of the above array:")
print(unique_result)

In [ ]:
88.编写一个NumPy程序来替换numpy数组中大于指定数组的所有元素。

In [ ]:
import numpy as np
x = np.array([[ 0.42436315, 0.48558583, 0.32924763], [ 0.7439979,0.58220701,0.38213418], [ 0.5097581,0.34528799,0.1563123 ]])
print("Original array:")
print(x)
print("Replace all elements of the said array with .5 which are greater than .5")
x[x > .5] = .5
print(x)

In [ ]:
89.编写一个NumPy程序以删除numpy数组中的特定元素。

In [ ]:
import numpy as np
x = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
index = [0, 3, 4]
print("Original array:")
print(x)
print("Delete first, fourth and fifth elements:")
new_x = np.delete(x, index)
print(new_x)

In [ ]:
90.编写一个NumPy程序，以删除带有0的numpy数组中的负值。

In [ ]:
import numpy as np
x = np.array([-1, -4, 0, 2, 3, 4, 5, -6])
print("Original array:")
print(x)
print("Replace the negative values of the said array with 0:")
x[x < 0] = 0
print(x)

In [ ]:
91.编写一个NumPy程序，以删除numpy数组中包含非数字值的所有行。

In [ ]:
import numpy as np
x = np.array([[1,2,3], [4,5,np.nan], [7,8,9], [True, False, True]])
print("Original array:")
print(x)
print("Remove all non-numeric elements of the said array")
print(x[~np.isnan(x).any(axis=1)])

In [ ]:
92.编写一个NumPy程序，以在numpy数组中选择满足多个条件的索引。

In [ ]:
import numpy as np
a = np.array([97, 101, 105, 111, 117])
b = np.array(['a','e','i','o','u'])
print("Original arrays")
print(a)
print(b)
print("Elements from the second array  corresponding to elements in the first array  that are greater than 100 and less than 110:")
print(b[(100 < a) & (a < 110)])

In [ ]:
93.编写一个NumPy程序，以numpy为单位获取向量的大小。

In [ ]:
import numpy as np
x = np.array([1,2,3,4,5])
print("Original array:")
print(x)
print("Magnitude of the vector:")
print(np.linalg.norm(x))

In [ ]:
94.编写一个NumPy程序，以计算numpy数组中唯一值的频率。

In [ ]:
import numpy as np
a = np.array( [10,10,20,10,20,20,20,30, 30,50,40,40] )
print("Original array:")
print(a)
unique_elements, counts_elements = np.unique(a, return_counts=True)
print("Frequency of unique values of the said array:")
print(np.asarray((unique_elements, counts_elements)))

In [ ]:
95.编写一个NumPy程序来检查numpy数组是否为空。

In [ ]:
import numpy as np
x = np.array([2, 3])
y = np.array([])
# size 2, array is not empty
print(x.size)
# size 0, array is empty
print(y.size)

In [ ]:
96.编写一个NumPy程序，将每一行除以一个矢量元素。

In [ ]:
import numpy as np
x = np.array([[20,20,20],[30,30,30],[40,40,40]])
print("Original array:")
print(x)
v = np.array([20,30,40])
print("Vector:")
print(v)
print(x / v[:,None])

In [ ]:
97.编写一个NumPy程序以打印数组的所有值。

In [ ]:
import numpy as np
np.set_printoptions(threshold=np.nan)
x = np.zeros((4, 4))
print(x)

In [ ]:
98.编写一个NumPy程序，将数组中的原始数据转换为二进制字符串，然后创建一个数组。

In [ ]:
import numpy as np
x = np.array([10, 20, 30], float)
print("Original array:")
print(x)
s = x.tostring()
print("Binary string array:")
print(s)
print("Array using fromstring():")
y = np.fromstring(s)
print(y)

In [ ]:
99.编写一个NumPy程序以求和并计算numpy数组元素的乘积。

In [ ]:
import numpy as np
x = np.array([10, 20, 30], float)
print("Original array:")
print(x)
print("Sum of the array elements:")
print(x.sum())
print("Product of the array elements:")
print(x.prod())

In [ ]:
100.编写一个NumPy程序以从源数组中获取值，并将其放在另一个数组的指定索引处。

In [6]:
import numpy as np
x = np.array([10, 10, 20, 30, 30], float)
print(x)
print("Put 0 and 40 in first and fifth position of the above array")
y = np.array([0, 40, 60], float) 
x.put([0, 4], y)
print("Array x, after putting two values:")
print(x)

[10. 10. 20. 30. 30.]
Put 0 and 40 in first and fifth position of the above array
Array x, after putting two values:
[ 0. 10. 20. 30. 40.]
