1.编写一个NumPy程序，对参数元素进行加、减、乘、除.

In [3]:
import numpy as np
print("Add:\n",np.add(2.0,3.0))
print("Subtract:\n",np.subtract(2.0,5.0))
print("Multiply:\n",np.multiply(2.0,2.0))
print("Divide:\n",np.divide(1.0,4.0))

Add:
 5.0
Subtract:
 -3.0
Multiply:
 4.0
Divide:
 0.25


2.编写一个NumPy程序来计算幂指数和的对数计算。

logaddexp(x1,x2)等于$\log(\exp(x1)+\exp(x2))$

logaddexp2(x1, x2)等于$\log_2(2^{x1} + 2^{x2})$

In [6]:
print("Logarithm of the sum of exponentiations:\n",np.logaddexp(0,1))
print("Logarithm of the sum of exponentiations of the inputs in base-2:\n",np.logaddexp2(4,4))

Logarithm of the sum of exponentiations:
 1.31326168752
Logarithm of the sum of exponentiations of the inputs in base-2:
 5.0


3.编写一个NumPy程序，得到下面数组。

Expected Output:

Original array:

[0 1 2 3 4 5 6 7 8 9]

Division of the array inputs, element-wise:

[ 0. 0.33333333 0.66666667 1. 1.33333333 1.6666666
7 2. 2.33333333 2.66666667 3. ]

In [9]:
print("Original array:\n",np.arange(0,10))

Original array:
 [0 1 2 3 4 5 6 7 8 9]


In [12]:
print("Division of the array inputs, element-wise:\n",np.linspace(0,3,10))

Division of the array inputs, element-wise:
 [ 0.          0.33333333  0.66666667  1.          1.33333333  1.66666667
  2.          2.33333333  2.66666667  3.        ]


4.编写一个NumPy程序,将对浮点数进行向下取整并返回整数的除法。

Expected Output:

Original array:

[1.0, 2.0, 3.0, 4.0]

Largest integer smaller or equal to the division of the inputs:

[ 0. 1. 2. 2.]

In [18]:
x=np.array([1.0,2.0,3.0,4.0])
print("Original array:\n",x)
print("Largest integer smaller or equal to the division of the inputs:\n",np.floor_divide(x, 1.5))

Original array:
 [ 1.  2.  3.  4.]
Largest integer smaller or equal to the division of the inputs:
 [ 0.  1.  2.  2.]


5.编写一个NumPy程序来获得数组值元素的能力。注：第一个数组元素从第二个数组提升为幂。

Expected Output:

Original array

[0 1 2 3 4 5 6]

First array elements raised to powers from second array, element-wise:

[ 0 1 8 27 64 125 216]

In [21]:
x=np.array([0,1,2,3,4,5,6],dtype=int)
print("Original array:\n",x)
print("First array elements raised to powers from second array, element-wise:\n",np.power(x,3))

Original array:
 [0 1 2 3 4 5 6]
First array elements raised to powers from second array, element-wise:
 [  0   1   8  27  64 125 216]


6.编写一个NumPy程序，以获取分区数组的元素的余数。

Sample Output:

Original array:

[0 1 2 3 4 5 6]

Element-wise remainder of division:

[0 1 2 3 4 0 1]

In [22]:
x=np.arange(7)
print("Original array:\n",x)
print("Element-wise remainder of division:\n",np.remainder(x,5))

Original array:
 [0 1 2 3 4 5 6]
Element-wise remainder of division:
 [0 1 2 3 4 0 1]


7.编写NumPy程序，计算元素的绝对值。

Sample output:

Original array:

[ -10.2 122.2 0.2]

Element-wise absolute value:

[ 10.2 122.2 0.2]

In [23]:
x=np.array([-10.2,122.2,0.2])
print("Original array:\n",x)
print("Element-wise absolute value:\n",np.absolute(x))

Original array:
 [ -10.2  122.2    0.2]
Element-wise absolute value:
 [  10.2  122.2    0.2]


8.编写一个NumPy程序，将数组元素保留到给定的小数。

round() 方法返回浮点数x的四舍五入值。

In [24]:
print(np.round([1.11,1.45,1.7,4.7]))

[ 1.  1.  2.  5.]


In [26]:
print(np.round([2.33,4.67,1.022,4.444],decimals=2))#decimals保留几位小数

[ 2.33  4.67  1.02  4.44]


9.编写NumPy程序，将数组的元素舍入最近的整数。

In [28]:
x=np.array([-0.91,-2.3,1.9,2.1])
print("Original array:\n",x)
print("Round elements of the array to the nearest integer:\n",np.rint(x))

Original array:
 [-0.91 -2.3   1.9   2.1 ]
Round elements of the array to the nearest integer:
 [-1. -2.  2.  2.]


10.编写一个NumPy程序来获取Numpy数组元素的下限、上限和截断值。

In [30]:
x=np.array([-0.91,-2.3,1.9,2.1])
print("Original array:\n",x)
print("Floor values of the above array elements:\n",np.floor(x))
print("Ceil values of the above array elements:\n",np.ceil(x))
print("Truncated values of the above array elements:\n",np.trunc(x))

Original array:
 [-0.91 -2.3   1.9   2.1 ]
Floor values of the above array elements:
 [-1. -3.  1.  2.]
Ceil values of the above array elements:
 [-0. -2.  2.  3.]
Truncated values of the above array elements:
 [-0. -2.  1.  2.]


11.编写一个NumPy程序，将一个5x3矩阵乘以一个3x2矩阵，并创建一个实矩阵乘积。

In [34]:
A=np.random.random((5,3))
B=np.random.random((3,2))
print("Dot product of two arrays:\n",np.dot(A,B))

Dot product of two arrays:
 [[ 0.65489958  1.13127721]
 [ 0.5933768   0.34973401]
 [ 0.34935506  0.2815315 ]
 [ 0.22388474  0.94092529]
 [ 0.73772751  0.354496  ]]


12.编写numpy程序,建立两个复数数组，并且做內积。

In [37]:
a=np.array([1-3j,5j,3+3j])
b=np.array([2,4j,1-4j])
print("Product of above two arrays:\n",np.vdot(a,b))

Product of above two arrays:
 (13-9j)


13.编写一个NumPy程序来创建两个数组的内积。

In [44]:
a=np.arange(15).reshape(3,5)
print("a:\n",a)
b=np.arange(5)
print("b:\n",b)
print("Inner of a and b arrays:\n",np.inner(a,b))

a:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
b:
 [0 1 2 3 4]
Inner of a and b arrays:
 [ 30  80 130]


14.编写Numpy程序，以生成矩阵和向量的内积、外积和交叉积。

In [46]:
x=np.array([1,2,3])
y=np.array([4,5,6])
print("Inner product of x and y:\n",np.inner(x,y))
print("Outer product of x and y:\n",np.outer(x,y))
print("Cross product of x and y:\n",np.cross(x,y))

Inner product of x and y:
 32
Outer product of x and y:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Cross product of x and y:
 [-3  6 -3]


15.编写一个NumPy程序，使两个数组相乘生成矩阵。

In [47]:
x = [[1, 0], [1, 1]]
y = [[3, 1], [2, 2]]
print("Matrix product of above two arrays:\n",np.matmul(x,y))

Matrix product of above two arrays:
 [[3 1]
 [5 3]]


16.编写一个NumPy程序，查找下列多项式的根。

a) $x^2 - 4x - 5$.

b) $x^4 - 11x^3 + 9x^2 + 11x - 10$

In [48]:
print("Roots of the first polynomial:\n",np.roots([1,-4,-5]))
print("Roots of the second polynomial:\n",np.roots([1,-11,9,11,-10]))

Roots of the first polynomial:
 [ 5. -1.]
Roots of the second polynomial:
 [ 10. +0.00000000e+00j  -1. +0.00000000e+00j   1. +9.63574370e-09j
   1. -9.63574370e-09j]


17.编写一个NumPy程序,来计算上面两个多项式值。

a)$x=4$

b)$x=2$

In [52]:
print("Polynomial value when x = 4:\n",np.polyval([1,-4,-5],4))
print("Polynomial value when x = 2:\n",np.polyval([1,-11,9,11,-10],2))

Polynomial value when x = 4:
 -5
Polynomial value when x = 2:
 -24


18.编写一个NumPy程序，多项式的加减乘除。

In [53]:
from numpy.polynomial import polynomial as P
x = (10,20,30)
y = (30,40,50)
print("Add one polynomial to another:\n",np.polyadd(x,y))
print("Subtract one polynomial from another:\n",np.polysub(x,y))
print("Multiply one polynomial by another:\n",np.polymul(x,y))
print("Divide one polynomial by another:\n",np.polydiv(x,y))

Add one polynomial to another:
 [40 60 80]
Subtract one polynomial from another:
 [-20 -20 -20]
Multiply one polynomial by another:
 [ 300 1000 2200 2200 1500]
Divide one polynomial by another:
 (array([ 0.33333333]), array([  6.66666667,  13.33333333]))


19.编写Numpy程序以计算二维Numpy阵列中的平均行数和列数。

In [54]:
x = np.array([[10, 30], [20, 60]])
print("Mean of each column:\n",x.mean(axis=0))
print("Mean of each row:",x.mean(axis=1))

Mean of each column:
 [ 15.  45.]
Mean of each row: [ 20.  40.]


20.编写一个NumPy程序，创建一个包含1000个元素的随机数组，并计算阵列元素的平均、方差、标准差。

In [60]:
x=np.random.random(1000)
print("Average of the array elements:\n",np.mean(x))
print("Standard deviation of the array elements:\n",np.std(x))
print("Variance of the array elements:\n",np.var(x))

Average of the array elements:
 0.496668220904
Standard deviation of the array elements:
 0.284923743155
Variance of the array elements:
 0.0811815394137


21.编写一个NumPy程序来计算以度为单位的角的三角正弦、余弦和切线数组。

In [62]:
print("sine: array of angles given in degrees:\n",np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print("cosine: array of angles given in degrees:\n",np.cos(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print("tangent: array of angles given in degrees:\n",np.tan(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))

sine: array of angles given in degrees:
 [ 0.          0.5         0.70710678  0.8660254   1.        ]
cosine: array of angles given in degrees:
 [  1.00000000e+00   8.66025404e-01   7.07106781e-01   5.00000000e-01
   6.12323400e-17]
tangent: array of angles given in degrees:
 [  0.00000000e+00   5.77350269e-01   1.00000000e+00   1.73205081e+00
   1.63312394e+16]


22.编写一个NumPy程序来计算给定数组中所有元素的反正弦、反余弦和反正切。

In [63]:
x = np.array([-1., 0, 1.])
print("Inverse sine:", np.arcsin(x))
print("Inverse cosine:", np.arccos(x))
print("Inverse tangent:", np.arctan(x))

Inverse sine: [-1.57079633  0.          1.57079633]
Inverse cosine: [ 3.14159265  1.57079633  0.        ]
Inverse tangent: [-0.78539816  0.          0.78539816]


23.编写Numpy程序以将角度从弧度转换为度。

In [1]:
import numpy as np
x = np.array([-np.pi, -np.pi/2, np.pi/2, np.pi])
r1 = np.degrees(x)
print(r1)

[-180.  -90.   90.  180.]


24.编写一个NumPy程序，将给定数组中所有元素的角度从度转换为弧度。

In [2]:
x = np.array([-180.,  -90.,   90.,  180.])
r1 = np.radians(x)
print(r1)

[-3.14159265 -1.57079633  1.57079633  3.14159265]


25.编写一个NumPy程序来计算给定数组中所有元素的双曲正弦、双曲余弦和双曲切线。

In [3]:
x = np.array([-1., 0, 1.])
print(np.sinh(x))
print(np.cosh(x))
print(np.tanh(x))

[-1.17520119  0.          1.17520119]
[ 1.54308063  1.          1.54308063]
[-0.76159416  0.          0.76159416]


26.编写Numpy程序，计算给定数组的around, floor, ceiling, truncated and round （到指定的小数位数）。

In [7]:
x = np.array([3.1, 3.5, 4.5, 2.9, -3.1, -3.5, -5.9])
print("Original array: ",x)
print("\naround:   ", np.around(x))#与round类似，对数组四舍五入
print("floor:    ",np.floor(x))#将x中各元素取比它小的最大的整数
print("ceil:     ",np.ceil(x))#将x中各元素取比它大的最小的整数
print("trunc:    ",np.trunc(x))#返回整数部分
print("round:    ",np.round(x))#将a四舍五入，精度由参数decimals决定，与around等价

Original array:  [ 3.1  3.5  4.5  2.9 -3.1 -3.5 -5.9]

around:    [ 3.  4.  4.  3. -3. -4. -6.]
floor:     [ 3.  3.  4.  2. -4. -4. -6.]
ceil:      [ 4.  4.  5.  3. -3. -3. -5.]
trunc:     [ 3.  3.  4.  2. -3. -3. -5.]
round:     [ 3.  4.  4.  3. -3. -4. -6.]


27.编写一个NumPy程序，计算给定轴上元素的累积和，数组的每一列的累积和，数组的每一行中的累积和。

In [10]:
x = np.array([[1,2,3], [4,5,6]])
print("Original array: ",x)
print("Cumulative sum of the elements along a given axis:",np.cumsum(x))
print("Sum over rows for each of the 3 columns:",np.cumsum(x,axis=0))
print("Sum over columns for each of the 2 rows:",np.cumsum(x,axis=1))

Original array:  [[1 2 3]
 [4 5 6]]
Cumulative sum of the elements along a given axis: [ 1  3  6 10 15 21]
Sum over rows for each of the 3 columns: [[1 2 3]
 [5 7 9]]
Sum over columns for each of the 2 rows: [[ 1  3  6]
 [ 4  9 15]]


28.编写一个NumPy程序来计算沿给定轴的元素的累积积，数组的每一列的累积积，数组的每一行中的累积积。

In [11]:
x = np.array([[1,2,3], [4,5,6]])
print("Original array: ",x)
print("Cumulative product of the elements along a given axis:",np.cumprod(x))
print("Product over rows for each of the 3 columns:",np.cumprod(x,axis=0))
print("Product over columns for each of the 2 rows:",np.cumprod(x,axis=1))

Original array:  [[1 2 3]
 [4 5 6]]
Cumulative product of the elements along a given axis: [  1   2   6  24 120 720]
Product over rows for each of the 3 columns: [[ 1  2  3]
 [ 4 10 18]]
Product over columns for each of the 2 rows: [[  1   2   6]
 [  4  20 120]]


29.编写一个NumPy程序来计算给定的数组的相邻元素之间的差异。

In [14]:
x = np.array([12,32,3,45,5,6])
print("Original array: ",x)
print("Difference between neighboring elements, element-wise of the said array.",np.diff(x))

Original array:  [12 32  3 45  5  6]
Difference between neighboring elements, element-wise of the said array. [ 20 -29  42 -40   1]


30.编写一个NumPy程序来计算相邻元素之间的差异，并将[0，0]和[200]添加到最后的数组中。

In [15]:
x = np.array([12,32,3,45,5,6])
print("Original array: ",x)
print(np.insert(np.append(np.diff(x), 200), 0, [0, 0]))

Original array:  [12 32  3 45  5  6]
[  0   0  20 -29  42 -40   1 200]


31.编写一个NumPy程序来计算给定数组中每个元素的$e^x$。

In [16]:
x = np.array([1,2,3,4,5,6])
print("Original array: ",x)
print(np.exp(x))

Original array:  [1 2 3 4 5 6]
[   2.71828183    7.3890561    20.08553692   54.59815003  148.4131591
  403.42879349]


32.编写一个NumPy程序来计算给定数组中每个元素的$e^x-1$。

In [17]:
x = np.array([1,2,3,4,5,6])
print("Original array: ",x)
print(np.exp(x)-1)

Original array:  [1 2 3 4 5 6]
[   1.71828183    6.3890561    19.08553692   53.59815003  147.4131591
  402.42879349]


33.编写一个NumPy程序来计算给定数组中所有元素的$2^x$。

In [22]:
x = np.array([1,2,3,4,5,8,10])
print("Original array: ",x)
print(np.exp2(x))

Original array:  [ 1  2  3  4  5  8 10]
[    2.     4.     8.    16.    32.   256.  1024.]


34.编写一个NumPy程序来计算给定数组中所有元素的自然对数、基为10和2的对数。

In [26]:
x = np.array([1,2,3,4,5,8,10])
print("Original array: ",x)
print("Natural log =", np.log(x))
print("Common log =", np.log10(x))
print("Base 2 log =", np.log2(x))

Original array:  [ 1  2  3  4  5  8 10]

 Natural log = [ 0.          0.69314718  1.09861229  1.38629436  1.60943791  2.07944154
  2.30258509]
Common log = [ 0.          0.30103     0.47712125  0.60205999  0.69897     0.90308999
  1.        ]
Base 2 log = [ 0.          1.          1.5849625   2.          2.32192809  3.
  3.32192809]


35.编写Numpy程序，以计算浮点精度中给定数组的每个元素的自然对数。

数据平滑处理 -- log1p( ) 和 exmp1( )

1.  数据预处理时首先可以对偏度比较大的数据用og1p函数进行转化，使其更加服从高斯分布，此步处理可能会使我们后续的分类结果得到一个好的结果。

2. 平滑问题很容易处理掉，导致模型的结果达不到一定的标准，log1p( )能够避免复值得问题 — 复值指一个自变量对应多个因变量


In [28]:
x = np.array([1.e-099,1.e-100])
print("Original array: ",x)
print("Natural logarithm of one plus each element", np.log1p(x))

Original array:  [  1.00000000e-099   1.00000000e-100]
Natural logarithm of one plus each element [  1.00000000e-099   1.00000000e-100]


36.编写一个NumPy程序来检查给定数组中设置了Signbit的元素是否正确/错误。

In [29]:
x=np.array([-1,-3,5,0,10,-8])
print("Original array: ",x)
print(np.signbit(x))

Original array:  [-1 -3  5  0 10 -8]
[ True  True False False False  True]


37.编写一个NumPy程序，复制第二个数组的符号给第一个数组。

In [34]:
a=np.array([-1,-3,5,0,10,-8])
print("Original array: ",a)
b=1.2
print("sign of b to a:",np.copysign(a,b))
print("sign of a to b:",np.copysign(b,a))

Original array:  [-1 -3  5  0 10 -8]
sign of b to a: [  1.   3.   5.   0.  10.   8.]
sign of a to b: [-1.2 -1.2  1.2  1.2  1.2 -1.2]


38.编写一个NumPy程序来计算给定数组中所有元素的数值相反数。

In [35]:
a=np.array([-1,-3,5,0,10,-8])
print("Original array: ",a)
print("Numerical negative value for all elements of the said array:\n", np.negative(a))

Original array:  [-1 -3  5  0 10 -8]
Numerical negative value for all elements of the said array:
 [  1   3  -5   0 -10   8]


39.编写一个NumPy程序来计算给定数组中所有元素的倒数。

In [43]:
a=np.array([-1.0,-3.0,0.5,-0.8])
print("Original array: ",a)
print("Reciprocal for all elements of the said array:\n",np.reciprocal(a))

Original array:  [-1.  -3.   0.5 -0.8]
Reciprocal for all elements of the said array:
 [-1.         -0.33333333  2.         -1.25      ]


40、编写NumPy程序以计算两个数组对应元素$x,y$的对应元素的$x^y$。

In [44]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[1, 2], [1, 2]])
print(np.power(x,y))

[[ 1  4]
 [ 3 16]]


41.编写一个NumPy程序来计算给定数组中所有元素的符号的元素级指示。


$$sign(x) =
\begin{cases}
1, \mbox{x>0} \\
0, \mbox{x=0}\\
-1,\mbox{x<0}
\end{cases}$$

In [45]:
a=np.array([-1,-3,5,0,10,-8])
print("Original array: ",a)
#大于０的数指示为１，小于０的数指示为－１
r1 = np.sign(a)
r2 = np.copy(a)
r2[r2 > 0] = 1
r2[r2 < 0] = -1
assert np.array_equal(r1, r2)
print("Element-wise indication of the sign for all elements of the said array:")
print(r1)

Original array:  [-1 -3  5  0 10 -8]
Element-wise indication of the sign for all elements of the said array:
[-1 -1  1  0  1 -1]


In [1]:
import numpy as np
a=np.array([-1,-3,5,0,10,-8])
print("Original array: ",a)
print(np.sign(a))

Original array:  [-1 -3  5  0 10 -8]
[-1 -1  1  0  1 -1]
