In [ ]:
编写一个NumPy程序，以沿第一个轴，最后一个轴和展平的数组对形状为2的给定数组进行排序
例子输出:
原始数组:
[[10 40]
[30 20]]
沿第一轴排序后:
[[10 20]
[30 40]]
沿最后一轴排序后:
[[10 40]
[20 30]]
展平后:
[10 20 30 40] 

In [ ]:
import numpy as np
a = np.array([[10,40],[30,20]])
print("Original array:")
print(a)
print("Sort the array along the first axis:")
print(np.sort(a, axis=0))
print("Sort the array along the last axis:")
print(np.sort(a))
print("Sort the flattened array:")
print(np.sort(a, axis=None))

In [ ]:
编写一个NumPy程序，根据给定的学生姓名，身高，班级及其数据类型创建结构化数组。 现在按高度排序数组
例子输出:
原始数组:
[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 )
(b'Pit', 5, 40.11)]
按高度排序后的数组:
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
(b'Nail', 6, 52.5 )]

In [ ]:
import numpy as np
data_type = [('name', 'S15'), ('class', int), ('height', float)]
students_details = [('James', 5, 48.5), ('Nail', 6, 52.5),('Paul', 5, 42.10), ('Pit', 5, 40.11)]
# create a structured array
students = np.array(students_details, dtype=data_type)   
print("Original array:")
print(students)
print("Sort by height")
print(np.sort(students, order='height')) 

In [ ]:
编写一个NumPy程序，根据给定的学生姓名，身高，班级及其数据类型创建结构化数组。 现在按类排序，如果类相等，则按高度排序
期望输出:
原始数组:
[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 ) (b'Pit', 5, 40.11)]
如果类相等，按高度排序后:
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 ) (b'Nail', 6, 52.5 )]

In [ ]:
import numpy as np
data_type = [('name', 'S15'), ('class', int), ('height', float)]
students_details = [('James', 5, 48.5), ('Nail', 6, 52.5),('Paul', 5, 42.10), ('Pit', 5, 40.11)]
# create a structured array
students = np.array(students_details, dtype=data_type)   
print("Original array:")
print(students)
print("Sort by class, then height if class are equal:")
print(np.sort(students, order=['class', 'height']))

In [ ]:
编写一个NumPy程序，根据给定的学生ID和身高，随着学生身高的增加对学生ID进行排序。 打印描述多列排序顺序的整数索引和排序后的数据
期望输出:
多列排序顺序的整数索引:
[4 0 5 3 6 1 2]
排序后:
1682 38.0
1023 40.0
5241 40.0
1671 41.0
4532 42.0
5202 42.0
6230 45.0

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
student_height = np.array([40., 42., 45., 41., 38., 40., 42.0])
#Sort by studen_id then by student_height
indices = np.lexsort((student_id, student_height))
print("Sorted indices:")
print(indices)
print("Sorted data:")
for n in indices:
  print(student_id[n], student_height[n])

In [ ]:
编写一个NumPy程序以获取给定数组的排序元素的索引
期望输出:
原始数组:
[1023 5202 6230 1671 1682 5241 4532]
给定数组的排序元素的索引:
[0 3 4 6 1 5 2]

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
print("Original array:")
print(student_id)
i = np.argsort(student_id)
print("Indices of the sorted elements of a given array:")
print(i)

In [ ]:
编写一个NumPy程序，首先使用实部，然后使用虚部对给定的复杂数组进行排序
注意:"busday”（星期一至星期五）的默认值为有效日期
原始数组:
[(1+2j), (3-1j), (3-2j), (4-3j), (3+5j)]
排序后:
[1.+2.j 3.-2.j 3.-1.j 3.+5.j 4.-3.j]

In [ ]:
import numpy as np
complex_num = [1 + 2j, 3 - 1j, 3 - 2j, 4 - 3j, 3 + 5j]
print("Original array:")
print(complex_num)
print("\nSorted a given complex array using the real part first, then the imaginary part.")
print(np.sort_complex(complex_num))

In [ ]:
编写一个NumPy程序，以给定数组在指定位置进行分区，并将所有较小的元素值以任意顺序（基于随机选择）移至分区的左侧，其余值移至右侧
输出:
原始数组:
[ 70 50 20 30 -11 60 50 40]
在4的位置分区:
[-11 30 20 40 50 50 60 70]

In [ ]:
import numpy as np
nums = np.array([70, 50, 20, 30, -11, 60, 50, 40])
print("Original array:")
print(nums)
print("\nAfter partitioning on 4 the position:")
print(np.partition(nums, 4))

In [ ]:
编写一个NumPy程序以从给定数组的开头对指定数量的元素进行排序
例子输出:
原始数组:
[0.39536213 0.11779404 0.32612381 0.16327394 0.98837963 0.25510787 0.01398678 0.15188239 0.12057667 0.67278699]
排序后:
[0.01398678 0.11779404 0.12057667 0.15188239 0.16327394 0.25510787 0.39536213 0.98837963 0.32612381 0.67278699]

In [ ]:
import numpy as np
nums =  np.random.rand(10)
print("Original array:")
print(nums)
print("\nSorted first 5 elements:")
print(nums[np.argpartition(nums,range(5))])