In [ ]:
编写一个Python程序来查找给定展平数组的最大值和最小值。
预期输出：
原始展平的数组：
[[0 1]
[2 3]]
上述展平的数组的最大值：
3 
以上展平的数组的最小值：
0

In [ ]:
import numpy as np
a = np.arange(4).reshape((2,2))
print("Original flattened array:")
print(a)
print("Maximum value of the above flattened array:")
print(np.amax(a))
print("Minimum value of the above flattened array:")
print(np.amin(a))


In [ ]:
编写一个NumPy程序，以沿第二个轴获取给定数组的最小值和最大值。
预期输出：
原始数组：
[[0 1]
[2 3]]
沿第二个轴的最大值：
[1 3]
沿第二个轴的最小值：
[0 2]

In [ ]:
import numpy as np
x = np.arange(4).reshape((2, 2))
print("\nOriginal array:")
print(x)
print("\nMaximum value along the second axis:")
print(np.amax(x, 1))
print("Minimum value along the second axis:")
print(np.amin(x, 1))


In [ ]:
3.编写一个NumPy程序，以计算沿第二个轴的给定数组的最大值和最小值之间的差。
预期输出：
原始数组：
[[0 1 2 3 4 5]
[6 7 8 9 10 11]]
所述数组的最大值和最小值之差：
[5 5]

In [ ]:
import numpy as np
x = np.arange(12).reshape((2, 6))
print("\nOriginal array:")
print(x)
r1 = np.ptp(x, 1)
r2 = np.amax(x, 1) - np.amin(x, 1)
assert np.allclose(r1, r2)
print("\nDifference between the maximum and the minimum values of the said array:")
print(r1)


In [ ]:
编写一个NumPy程序，以计算沿第二个轴的给定数组中所有元素的第80个百分位数。
预期输出：
原始数组：
[1.0、2.0、3.0、4.0]
最大整数，小于或等于输入的除法：
[0. 1. 2. 2.]

In [ ]:
import numpy as np
x = np.arange(12).reshape((2, 6))
print("\nOriginal array:")
print(x)
r1 = np.percentile(x, 80, 1)
print("\n80th percentile for all elements of the said array along the second axis:")
print(r1)


In [ ]:
编写一个NumPy程序以计算平展给定数组的中位数。
注：第一个数组元素从第二个数组提升为幂
预期输出：
原始数组：
[[0 1 2 3 4 5]
[6 7 8 9 10 11]]
所述数组的中位数：
5.5

In [ ]:
import numpy as np
x = np.arange(12).reshape((2, 6))
print("\nOriginal array:")
print(x)
r1 =  np.median(x)
print("\nMedian of said array:")
print(r1)


In [ ]:
编写一个NumPy程序以计算给定数组的权重。
样本输出：
原始数组：
[0 1 2 3 4]
该数组的加权平均值：
2.6666666666666665

In [ ]:
import numpy as np
x = np.arange(5)
print("\nOriginal array:")
print(x)
weights = np.arange(1, 6)
r1 = np.average(x, weights=weights)
r2 = (x*(weights/weights.sum())).sum()
assert np.allclose(r1, r2)
print("\nWeighted average of the said array:")
print(r1)


In [ ]:
编写一个NumPy程序，以计算沿第二个轴的给定数组的均值，标准差和方差。
示例输出：
原始数组：
[0 1 2 3 4 5]
均值：2.5
std：1
方差：2.9166666666666665

In [ ]:
import numpy as np
x = np.arange(6)
print("\nOriginal array:")
print(x)
r1 = np.mean(x)
r2 = np.average(x)
assert np.allclose(r1, r2)
print("\nMean: ", r1)
r1 = np.std(x)
r2 = np.sqrt(np.mean((x - np.mean(x)) ** 2 ))
assert np.allclose(r1, r2)
print("\nstd: ", 1)
r1= np.var(x)
r2 = np.mean((x - np.mean(x)) ** 2 )
assert np.allclose(r1, r2)
print("\nvariance: ", r1)


In [ ]:
编写一个NumPy程序来计算两个给定数组的协方差矩阵。
样本输出：
原始array1：
[0 1 2]
原始array1：
[2 1 0]
所述数组的协方差矩阵：
[[1. -1。]
[-1。1.]]

In [ ]:
import numpy as np
x = np.array([0, 1, 2])
y = np.array([2, 1, 0])
print("\nOriginal array1:")
print(x)
print("\nOriginal array1:")
print(y)
print("\nCovariance matrix of the said arrays:\n",np.cov(x, y))


In [ ]:
编写一个NumPy程序来计算两个给定数组的互相关。
示例输出：
原始array1：
[0 1 3]
原始array1：
[2 4 5]
所述数组的互相关：
[[2.33333333 2.16666667]
[2.16666667 2.33333333]]

In [ ]:
import numpy as np
x = np.array([0, 1, 3])
y = np.array([2, 4, 5])
print("\nOriginal array1:")
print(x)
print("\nOriginal array1:")
print(y)
print("\nCross-correlation of the said arrays:\n",np.cov(x, y))


In [ ]:
编写一个NumPy程序来计算两个给定数组的皮尔逊积矩相关系数。
样本输出：
原始array1：
[0 1 3]
原始array1：
[2 4 5]
所述阵列的Pearson积矩相关系数：
[[1。0.92857143]
[0.92857143 1.]]

In [ ]:
import numpy as np
x = np.array([0, 1, 3])
y = np.array([2, 4, 5])
print("\nOriginal array1:")
print(x)
print("\nOriginal array1:")
print(y)
print("\nPearson product-moment correlation coefficients of the said arrays:\n",np.corrcoef(x, y))


In [ ]:
编写一个NumPy程序，以测试给定数组的元素方式的有限性（非无穷大或不是数字），NaN，NaT，NaT（非时间），负无穷大，正无穷大。
样本输出：
测试元素方式的有限性（不是无穷大或不是一个数字）：
True
是
False
测试元素方式的正或负无穷大：
True
False
True
测试元素方式的NaN：
[True False False ]
对NaT（不是时间） 逐个元素进行测试：
[True False]
对负无穷大进行逐个元素测试：
[1 0 0]
对正无穷大进行逐个元素测试：
[0 0 1]

In [ ]:
import numpy as np
print("\nTest element-wise for finiteness (not infinity or not Not a Number):")
print(np.isfinite(1))
print(np.isfinite(0))
print(np.isfinite(np.nan))
print("\nTest element-wise for positive or negative infinity:")
print(np.isinf(np.inf))
print(np.isinf(np.nan))
print(np.isinf(np.NINF))
print("Test element-wise for NaN:")
print(np.isnan([np.log(-1.),1.,np.log(0)]))
print("Test element-wise for NaT (not a time):")
print(np.isnat(np.array(["NaT", "2016-01-01"], dtype="datetime64[ns]")))
print("Test element-wise for negative infinity:")
x = np.array([-np.inf, 0., np.inf])
y = np.array([2, 2, 2])
print(np.isneginf(x, y))
print("Test element-wise for positive infinity:")
x = np.array([-np.inf, 0., np.inf])
y = np.array([2, 2, 2])
print(np.isposinf(x, y))


In [ ]:
编写一个Python NumPy程序来计算沿给定展平数组的指定轴的加权平均值。
来自Wikipedia：加权算术平均值类似于普通算术平均值（最常见的平均值类型），不同之处在于，不是每个数据点对最终平均值的贡献均相等，而是一些数据点的贡献大于其他平均值。加权均值的概念在描述性统计中发挥作用，并且在其他几个数学领域也以更一般的形式出现。
样本输出：
原始展平的数组：
[[0 1 2]
[3 4 5]
[6 7 8]]
沿上述展平的数组的指定轴的加权平均值：
[1.2 4.2 7.2]

In [ ]:
import numpy as np
a = np.arange(9).reshape((3,3))
print("Original flattened array:")
print(a)
print("Weighted average along the specified axis of the above flattened array:")
print(np.average(a, axis=1, weights=[1./4, 2./4, 2./4]))


In [ ]:
编写一个Python程序，以计算给定非负整数数组中每个值的出现次数。
注意：bincount（）函数对非负整数数组中每个值在最小值和最大值之间的范围（包括未发生的值）之间的出现次数进行计数。
示例输出：
原始数组：
[0，1，6，1，4，1，2，2，7]
数组中每个值的出现次数：
[1 3 2 0 1 0 1 1]

In [ ]:
import numpy as np
array1 = [0, 1, 6, 1, 4, 1, 2, 2, 7] 
print("Original array:")
print(array1)
print("Number of occurrences of each value in array: ")
print(np.bincount(array1))


In [ ]:
编写一个NumPy程序，计算相对于垃圾箱的nums的直方图。
示例输出：
nums：[0.5 0.7 1. 1.2 1.3 2.1]
bins：[0 1 2 3]
结果：（array（[2，3，1]，dtype = int64），array（[0，1 ，2，3]））

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
nums = np.array([0.5, 0.7, 1.0, 1.2, 1.3, 2.1])
bins = np.array([0, 1, 2, 3])
print("nums: ",nums)
print("bins: ",bins)
print("Result:", np.histogram(nums, bins))
plt.hist(nums, bins=bins)
plt.show()


In [ ]:
编写一个NumPy程序以显示2017年3月的所有日期。
预期输出：
2017年3月
['2017-03-01''2017-03-02''2017-03-03 '
'2017-03-04''2017-03-05''2017-03-06''2017-03-07''2017-03-08''2017-03-09''2017-03-10'
'
2017-03-11''2017-03-12''2017-03-13''2017-03-14''2017-03-15''2017-03-16''2017-03-17'' 2017年3月18'日‘2017年3月19日’‘二○一七年三月二十〇日’
‘2017年3月21日’‘2017年3月22日’‘2017年3月23日’‘2017年3月24日’“2017 -03-25''2017-03-26''2017-03-27''2017-03-28''2017-03-29
''2017-03-30''2017-03-31'
]

In [ ]:
import numpy as np
print("March, 2017")
print(np.arange('2017-03', '2017-04', dtype='datetime64[D]'))


In [ ]:
编写一个NumPy程序以获取昨天，今天和明天的日期。
样本输出：
昨天：2017-03-24
今天：2017-03-25
明天：2017-03-26

In [ ]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)


In [ ]:
编写一个NumPy程序以计算特定月份的天数
预期输出：
2016年2
月的天
数：29天2017年2
月的天
数：
28天2018年2 月的天数：28天

In [ ]:
import numpy as np
print("Number of days, February, 2016: ")
print(np.datetime64('2016-03-01') - np.datetime64('2016-02-01'))
print("Number of days, February, 2017: ")
print(np.datetime64('2017-03-01') - np.datetime64('2017-02-01'))
print("Number of days, February, 2018: ")
print(np.datetime64('2018-03-01') - np.datetime64('2018-02-01'))


In [ ]:
编写一个NumPy程序以创建24个python datetime.datetime对象（每小时一个对象），然后将其放在numpy数组中。
预期输出：
[datetime.datetime（2000，1，1，1，0，0）
datetime.datetime（2000，1，1，1，1，0 ）datetime.datetime（2000，1，1，2，0） datetime.datetime（2000，1，1，3，0）
datetime.datetime（2000，1，1，4，0）
datetime.datetime（2000，1，1，5，0 ）datetime.datetime（2000，1， 1，6，0）datetime.datetime（2000，1，1，7，0）datetime.datetime（
2000，1，1，8，0）datetime.datetime（
2000，1，1，9，0 ）datetime。 datetime（2000，1，1，1，10，0）datetime.datetime（
2000，1，1，11，0）datetime.datetime（2000，1，1，12，12，0）datetime.datetime（2000，1，1， 13、0）
datetime.datetime（2000，1，1，14，0）datetime.datetime（
2000，1，1，15，0）datetime.datetime（2000，1，1，16，16，0）datetime.datetime（2000，1，
1，17，0 ）datetime.datetime（2000，1，1，1，18，0 ）datetime.datetime（2000，1，1，19，0）
datetime.datetime（2000，1，1，20，0）datetime。 datetime（2000，1，1，21，0）
datetime.datetime（2000，1，1，22，0 ）datetime.datetime（2000，1，1，23，0）]

In [ ]:
import numpy as np
import datetime
start = datetime.datetime(2000, 1, 1)
dt_array = np.array([start + datetime.timedelta(hours=i) for i in range(24)])
print(dt_array)


In [ ]:
编写一个NumPy程序以查找2017年5月的第一个星期一
预期的输出：
2017年5月的第一个星期一：
2017-05-01

In [ ]:
import numpy as np
print("First Monday in May 2017:")
print(np.busday_offset('2017-05', 0, roll='forward', weekmask='Mon'))


In [ ]:
编写一个NumPy程序以查找2017年3月的工作日数。
注意：周一至周五的默认“ busday”为有效日。
样本输出：
2017年3月的工作日数：
23

In [ ]:
import numpy as np
print("Number of weekdays in March 2017:")
print(np.busday_count('2017-03', '2017-04'))


In [ ]:
编写一个NumPy程序，将numpy datetime64转换为Timestamp。
样本输出：
当前日期：
2017-04-01 08：01：12.722055
时间戳：
1491033672.72
来自时间戳的UTC：
2017-04-01 08：01：12.722055

In [ ]:
import numpy as np
from datetime import datetime
dt = datetime.utcnow()
print("Current date:")
print(dt)
dt64 = np.datetime64(dt)
ts = (dt64 - np.datetime64('1970-01-01T00:00:00Z')) / np.timedelta64(1, 's')
print("Timestamp:")
print(ts)
print("UTC from Timestamp:")
print(datetime.utcfromtimestamp(ts))


In [ ]:
编写一个NumPy程序，以元素方式串联两个字符串数组。
预期的输出：
Array1：
[' Python''PHP ']
Array2：
[' Java''C ++']
新数组：
['Python Java''PHP C ++']

In [ ]:
import numpy as np
x1 = np.array(['Python', 'PHP'], dtype=np.str)
x2 = np.array([' Java', ' C++'], dtype=np.str)
print("Array1:")
print(x1)
print("Array2:")
print(x2)
new_array = np.char.add(x1, x2)
print("new array:")
print(new_array)


In [ ]:
编写一个NumPy程序，将给定字符串数组的所有元素重复三次。
预期输出：
原始 数组： ['Python''PHP''Java''C
++']
新数组：
['PythonPythonPython' 'PHPPHPPHP''JavaJavaJava''C ++ C ++ C ++']

In [ ]:
import numpy as np
x1 = np.array(['Python', 'PHP', 'Java', 'C++'], dtype=np.str)
print("Original Array:")
print(x1)
new_array = np.char.multiply(x1, 3)
print("New array:")
print(new_array)


In [ ]:
编写一个NumPy程序，将给定数组的所有元素的首字母，小写字母，大写字母，swapcase字母，title-case字母大写。
预期输出：
原始数组：
['python''PHP''java''C ++']
大写：['Python''Php''Java''C ++']
降低：['python''php''
java''c ++'] 首字母大写：['PYTHON''PHP''JAVA''C ++'] 换行：['
PYTHON''php''JAVA''c ++']
标题大写：['Python''Php''Java' [C ++]]

In [ ]:
import numpy as np
x = np.array(['python', 'PHP', 'java', 'C++'], dtype=np.str)
print("Original Array:")
print(x)
capitalized_case = np.char.capitalize(x)
lowered_case = np.char.lower(x)
uppered_case = np.char.upper(x)
swapcased_case = np.char.swapcase(x)
titlecased_case = np.char.title(x)
print("\nCapitalized: ", capitalized_case)
print("Lowered: ", lowered_case)
print("Uppered: ", uppered_case)
print("Swapcased: ", swapcased_case)
print("Titlecased: ", titlecased_case)


In [ ]:
编写一个NumPy程序，以使给定数组的每个元素15的长度以及以_为填充的字符串居中/左对齐/右对齐。
原始数组：
['python练习''
PHP''java''C ++'] 居中= ['python练习''______PHP______''______java_____''______ C ++ ______']左= ['python练习'' PHP____________''java___________''C ++ ____________']右= ['python锻炼''__________PHP''___________java''____________ C ++']

In [ ]:
import numpy as np
x = np.array(['python exercises', 'PHP', 'java', 'C++'], dtype=np.str)
print("Original Array:")
print(x)
centered = np.char.center(x, 15, fillchar='_')
left = np.char.ljust(x, 15, fillchar='_')
right = np.char.rjust(x, 15, fillchar='_')
print("\nCentered =", centered)
print("Left =", left)
print("Right =", right)


In [ ]:
编写一个NumPy程序，在给定数组的所有元素的字符之间插入空格。
注意：第一个数组元素由第二个数组提升为幂
预期输出：
原始数组：
['python Exercises''PHP''java''C ++']
['pythonexercises''PHP''java''C ++ ']

In [ ]:
import numpy as np
x = np.array(['python exercises', 'PHP', 'java', 'C++'], dtype=np.str)
print("Original Array:")
print(x)
r = np.char.join(" ", x)
print(r)


In [ ]:
编写一个NumPy程序，以在cp500中编码给定数组的所有元素，然后再次对其进行解码。
示例输出：
编码= [b'\ x97 \ xa8 \ xa3 \ x88 \ x96 \ x95 @ \ x85 \ xa7 \ x85 \ x99 \ x83 \ x89 \ xa2 \ x85 \ xa2'b
'\ xd7 \ xc8 \ xd7'b'\ x91 \ x81 \ xa5 \ x81'b'\ xc3NN']
已解码= ['python练习'' PHP''java''C ++']

In [ ]:
import numpy as np
x = np.array(['python exercises', 'PHP', 'java', 'C++'], dtype=np.str)
print("Original Array:")
print(x)
encoded_char = np.char.encode(x, 'cp500')
decoded_char = np.char.decode(encoded_char,'cp500')
print("\nencoded =", encoded_char)
print("decoded =", decoded_char)


In [ ]:
编写一个NumPy程序，以删除给定数组的所有元素的前导和尾随空格。
样本输出：
原始数组：
[-10.2 122.2 0.2]逐
元素的绝对值：
[10.2 122.2 0.2]

In [ ]:
import numpy as np
x = np.array([' python exercises ', ' PHP  ', ' java  ', '  C++'], dtype=np.str)
print("Original Array:")
print(x)
stripped = np.char.strip(x)
print("\nRemove the leading and trailing whitespaces: ", stripped)


In [ ]:
编写一个NumPy程序，以删除给定数组的所有元素的前导空格。
样本输出：
原始数组：
['python练习''PHP''java''C ++']
删除前导空格：['python练习'PHP'Java'C ++']

In [ ]:
import numpy as np
x = np.array([' python exercises ', ' PHP  ', ' java  ', '  C++'], dtype=np.str)
print("Original Array:")
print(x)
lstripped_char = np.char.lstrip(x)
print("\nRemove the leading whitespaces : ", lstripped_char)


In [ ]:
编写一个NumPy程序，以删除给定数组的所有元素的尾随空格。
样本输出：
原始数组：
['python练习''PHP''java''C ++']
删除结尾的空格：['python练习''PHP''java''C ++']

In [ ]:
import numpy as np
x = np.array([' python exercises ', ' PHP  ', ' java  ', '  C++'], dtype=np.str)
print("Original Array:")
print(x)
rstripped_char = np.char.rstrip(x)
print("\nRemove the trailing whitespaces : ", rstripped_char)


In [ ]:
编写一个NumPy程序，以空格分隔给定数组的元素。
示例输出：
原始数组：
['Python PHP Java C ++']
用空格分割所述数组的元素：
[list（['Python'，'PHP'，'Java'，'C ++']）]

In [ ]:
import numpy as np
x = np.array(['Python PHP Java C++'], dtype=np.str)
print("Original Array:")
print(x)
r = np.char.split(x)
print("\nSplit the element of the said array with spaces: ")
print(r)


In [ ]:
编写一个NumPy程序，将给定数组的元素拆分为多行。
样本输出：
原始数组：
['Python \\ Exercises，练习，解决方案']
[列表（['Python \\ Exercises，练习，解决方案']）]

In [ ]:
import numpy as np
x = np.array(['Python\Exercises, Practice, Solution'], dtype=np.str)
print("Original Array:")
print(x)
r = np.char.splitlines(x)
print(r)


In [ ]:
编写一个NumPy程序，将一个矩阵乘以另一个复数矩阵，并创建一个新的复数矩阵。
示例输出：
原始数组：
[ '2''11''234''1234''12345' ]
5位数字的零数字字符串：
['00002''00011''00234''01234''12345 ']

In [ ]:
import numpy as np
x = np.array(['2', '11', '234', '1234', '12345'], dtype=np.str)
print("\nOriginal Array:")
print(x)
r = np.char.zfill(x, 5)
print("\nNumeric string of 5 digits with zeros:")
print(r) 


In [ ]:
编写一个NumPy程序，在给定数组的元素中将“ PHP”替换为“ Python”。
样本输出：
原始数组：
['PHP练习，实践，解决方案']
新数组：
['Python练习，实践，解决方案']

In [ ]:
import numpy as np
x = np.array(['PHP Exercises, Practice, Solution'], dtype=np.str)
print("\nOriginal Array:")
print(x)
r = np.char.replace(x, "PHP", "Python")
print("\nNew array:")
print(r)


In [ ]:
编写一个NumPy程序，对两个给定数组的所有元素进行相等，不相等，更大相等，更大或更小的测试。
预期输出：
Array1：
[' Hello''PHP''JS''examples''html ']
Array2：
[' Hello''php''Java''examples''html ']
相等测试：
[True False False True True]
不相等的测试：
[False True True False False]
较少相等的测试：
[True True True True True True]
较高的相等测试：
[True False False True True]
较少的测试：
[False True True False False]

In [ ]:
import numpy as np
x1 = np.array(['Hello', 'PHP', 'JS', 'examples', 'html'], dtype=np.str)
x2 = np.array(['Hello', 'php', 'Java', 'examples', 'html'], dtype=np.str)
print("\nArray1:")
print(x1)
print("Array2:")
print(x2)
print("\nEqual test:")
r = np.char.equal(x1, x2)
print(r)
print("\nNot equal test:")
r = np.char.not_equal(x1, x2)
print(r)
print("\nLess equal test:")
r = np.char.less_equal(x1, x2)
print(r)
print("\nGreater equal test:")
r = np.char.greater_equal(x1, x2)
print(r)
print("\nLess test:")
r = np.char.less(x1, x2)
print(r)


In [ ]:
编写一个NumPy程序，以元素方式计算给定数组中“ P”的数量。
样本输出：
原始数组：
['Python''PHP''JS''examples''html']
'P'的数量：
[1 2 0 0 0]

In [ ]:
import numpy as np
x1 = np.array(['Python', 'PHP', 'JS', 'examples', 'html'], dtype=np.str)
print("\nOriginal Array:")
print(x1)
print("Number of ‘P’:")
r = np.char.count(x1, "P")
print(r)


In [ ]:
编写一个NumPy程序，以元素方式计算给定数组中“ P”的最低索引。
原始数组”：
['Python''PHP''JS''示例''HTML']
计算'P'的最低索引：
[0 0 -1 4 -1]

In [ ]:
import numpy as np
x1 = np.array(['Python', 'PHP', 'JS', 'EXAMPLES', 'HTML'], dtype=np.str)
print("\nOriginal Array:")
print(x1)
print("count the lowest index of ‘P’:")
r = np.char.find(x1, "P")
print(r)


In [ ]:
编写一个NumPy程序，检查给定数组的每个元素是否仅由数字，仅小写字母和仅大写字母组成。
示例输出：
原始数组：
['Python''PHP''JS''示例''html5''5']
仅数字= [False False False False False True]
仅小写= [False False False False False True False]
仅大写= [False True True False False False False]

In [ ]:
import numpy as np
x = np.array(['Python', 'PHP', 'JS', 'Examples', 'html5', '5'], dtype=np.str)
print("\nOriginal Array:")
print(x)
r1 = np.char.isdigit(x)
r2 = np.char.islower(x)
r3 = np.char.isupper(x)
print("Digits only =", r1)
print("Lower cases only =", r2)
print("Upper cases only =", r3)


In [ ]:
编写一个NumPy程序，以检查给定数组的每个元素是否以“ P”开头。
示例输出：
原始数组：
['Python''PHP''JS''examples''html']
测试所说数组的每个元素是否以'P'开头：
[True True False False False]

In [ ]:
import numpy as np
x1 = np.array(['Python', 'PHP', 'JS', 'examples', 'html'], dtype=np.str)
print("\nOriginal Array:")
print(x1)
print("Test if each element of the said array starts with 'P':")
r = np.char.startswith(x1, "P")
print(r)
